version: '3'

services:
    web:
        image: matthiasnoback/php_workshop_tools_simple_webserver
        command: public/
        volumes:
            - ./:/opt:cached
        ports:
            - 8080:8080
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=web"
            DB_PATH: /opt/var
            APPLICATION_ENV: development
        user: ${HOST_UID}:${HOST_GID}

    devtools:
        build: docker/devtools/
        image: matthiasnoback/advanced_testing_workshop_devtools
        volumes:
            - ./:/opt:cached
            - ${COMPOSER_HOME}:/home/.composer:cached
        environment:
            COMPOSER_HOME: /home/.composer
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            WEB_HOSTNAME: web
            DB_PATH: /opt/var
        user: ${HOST_UID}:${HOST_GID}
